export enum Platform {
  PS1 = 'PS1',
  PS2 = 'PS2',
  PS3 = 'PS3',
  PS4 = 'PS4',
  PS5 = 'PS5',
  PSP = 'PSP',
  PSVITA = 'PSVITA',
  NES = 'NES',
  SNES = 'SNES',
  N64 = 'N64',
  GC = 'GC',
  WII = 'WII',
  WIIU = 'WIIU',
  SWITCH = 'SWITCH',
  GB = 'GB',
  GBC = 'GBC',
  GBA = 'GBA',
  DS = 'DS',
  '3DS' = '3DS',
  MS = 'MS',
  MD = 'MD',
  SS = 'SS',
  DC = 'DC',
  GG = 'GG',
  XBOX = 'XBOX',
  X360 = 'X360',
  XONE = 'XONE',
  XSERIES = 'XSERIES',
  ATARI = 'ATARI',
  NEOGEO = 'NEOGEO',
  PCE = 'PCE',
  GEN = 'GEN',
}

export const PlatformLabels: Record<Platform, string> = {
  [Platform.PS1]: 'PlayStation 1',
  [Platform.PS2]: 'PlayStation 2',
  [Platform.PS3]: 'PlayStation 3',
  [Platform.PS4]: 'PlayStation 4',
  [Platform.PS5]: 'PlayStation 5',
  [Platform.PSP]: 'PlayStation Portable',
  [Platform.PSVITA]: 'PlayStation Vita',
  [Platform.NES]: 'Nintendo Entertainment System',
  [Platform.SNES]: 'Super Nintendo',
  [Platform.N64]: 'Nintendo 64',
  [Platform.GC]: 'Nintendo GameCube',
  [Platform.WII]: 'Nintendo Wii',
  [Platform.WIIU]: 'Nintendo Wii U',
  [Platform.SWITCH]: 'Nintendo Switch',
  [Platform.GB]: 'Game Boy',
  [Platform.GBC]: 'Game Boy Color',
  [Platform.GBA]: 'Game Boy Advance',
  [Platform.DS]: 'Nintendo DS',
  [Platform['3DS']]: 'Nintendo 3DS',
  [Platform.MS]: 'Sega Master System',
  [Platform.MD]: 'Sega Mega Drive',
  [Platform.SS]: 'Sega Saturn',
  [Platform.DC]: 'Sega Dreamcast',
  [Platform.GG]: 'Sega Game Gear',
  [Platform.XBOX]: 'Xbox Original',
  [Platform.X360]: 'Xbox 360',
  [Platform.XONE]: 'Xbox One',
  [Platform.XSERIES]: 'Xbox Series X/S',
  [Platform.ATARI]: 'Atari 2600',
  [Platform.NEOGEO]: 'Neo Geo',
  [Platform.PCE]: 'PC Engine',
  [Platform.GEN]: 'Genérica / PC',
};
